In [1]:
import numpy as np

In [2]:
x = np.array(1)

In [3]:
x

array(1)

In [4]:
x.ndim

0

In [5]:
y = np.array([1, 2, 3])

In [6]:
y

array([1, 2, 3])

In [7]:
y.ndim

1

In [8]:
z = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [9]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
z.ndim

2

In [11]:
n_z = np.array([z, z*2, z*3])

In [12]:
n_z

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]]])

In [13]:
n_z.ndim

3

In [14]:
n_z.shape

(3, 3, 3)

In [15]:
n_z.dtype

dtype('int64')

In [16]:
def my_add(a, b):
    a = a.copy()
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            a[i, j] += b[i, j]
    return a

In [17]:
a = np.array([[1,1],
              [1,1]])

b = np.array([[1,2],
              [3,4]])

In [18]:
my_add(a, b)

array([[2, 3],
       [4, 5]])

In [19]:
a + b

array([[2, 3],
       [4, 5]])

In [20]:
a = np.array([1, 2])
b = np.array([3, 4])
# a*b = 1*3 + 2*4 = 11
np.dot(a, b) 

11

In [21]:
a = np.array([[1,1],
              [2,2]])
b = np.array([3,4])
# a*b = [1*3+1*4, 2*3+2*4] = [7, 14]
np.dot(a, b)

array([ 7, 14])

In [22]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[1,2],
              [3,4]])
# a*b = [[1*1+2*3, 1*2+2*4], = [[ 7, 10],
#        [3*1+4*3, 3*2+4*4]]    [15, 22]]
np.dot(a, b)

array([[ 7, 10],
       [15, 22]])

In [23]:
a = np.array([[ 7, 10],
              [15, 22]])

In [24]:
a.shape

(2, 2)

In [25]:
a = a.reshape(1, 4)
a

array([[ 7, 10, 15, 22]])

In [26]:
a = a.reshape(4,1)
a

array([[ 7],
       [10],
       [15],
       [22]])

In [27]:
# a[i, :] --- transpose ---> a[:, i]
np.transpose(a)

array([[ 7, 10, 15, 22]])